### ISSUE TITLE
couldn't register topic with msgpack-1.0.0

### ISSUE THREAD

**Issue by freedai** [opendxl/opendxl-client-python#48]
With newly build docker image, notice it's pulling msgpack-1.0.0 and it failed to register topic with follwoing error. Switch back to msgpack-0.6.2 solved the problem. Wondering if could do something in dxlclient to solve this issue. dxlbroker ran in old image.
```
docker.io/opendxl/opendxl-broker                                     latest              7a3343070a4a        3 months ago        261 MB
```

```
2020-02-18 20:10:20,756 gtdbapiservice.app INFO     Registering topic: /twapi/v1/cti/gtdb/domain/report
2020-02-18 20:10:20,759 dxlclient._thread_pool ERROR    Error in worker thread
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/dxlclient/_thread_pool.py", line 54, in run
    func(*args, **kargs)
  File "/usr/local/lib/python3.8/site-packages/dxlclient/client.py", line 1158, in _handle_message
    message = Message._from_bytes(payload)
  File "/usr/local/lib/python3.8/site-packages/dxlclient/message.py", line 372, in _from_bytes
    message._unpack_message(unpacker)
  File "/usr/local/lib/python3.8/site-packages/dxlclient/message.py", line 554, in _unpack_message
    super(Response, self)._unpack_message(unpacker)
  File "/usr/local/lib/python3.8/site-packages/dxlclient/message.py", line 224, in _unpack_message
    self._message_id = self._unpack_next_unicode_string(unpacker)
  File "/usr/local/lib/python3.8/site-packages/dxlclient/message.py", line 389, in _unpack_next_unicode_string
    return Message._decode_to_unicode_string(next(unpacker))
  File "/usr/local/lib/python3.8/site-packages/dxlclient/message.py", line 385, in _decode_to_unicode_string
    return None if obj is None else obj.decode('utf8')
AttributeError: 'str' object has no attribute 'decode'

```

**Comment by chrissmith-mcafee** [comment]
Thanks for the report, should be resolved in 5.6.0.3.
